### ISSUE TITLE
Malformed IRl exists in the closure of monarch.owl

### ISSUE THREAD

**Issue by yy20716** [monarch-initiative/dipper#553]
I was importing monarch data including its ontology to update the data for the [sparql endpoint](http://rdf.monarchinitiative.org). This process involves the step that generates the closure of [monarch.owl](https://github.com/monarch-initiative/monarch-ontology/blob/master/monarch.owl) as follows.

> OWLTOOLS_MEMORY=12G OWLTools-Runner/bin/owltools --log-error monarch.owl --merge-imports-closure -o -f turtle output.ttl

In the expanded file (i.e., output.ttl), I found the malformed url as follows.

> <http://zfin/definition/source_information>

In the closure, many entries such as [http://purl.obolibrary.org/obo/ZP_0013325](http://purl.obolibrary.org/obo/ZP_0013325) are described using this IRI. It's not clear yet, but I believe this url prevents me from importing the closure of monarch.owl (output.ttl) into the blazegraph store right now. Can anyone please check this issue? Thank you so much.

**Comment by kshefchek** [comment]
I suspect it's an issue with upheno or the ZP pipeline specifically.  cc @drseb @balhoff.  Maybe this has been fixed in the new pipeline https://github.com/Phenomics/zebrafish-phenotype-ontology-build

**Comment by yy20716** [comment]
Thank you for your tip. I downloaded and ran the source codes of that project (zebrafish-phenotype-ontology-build), but the same malformed IRI still exists. It seems that malformed IRI comes from [this code](https://github.com/Phenomics/zebrafish-phenotype-ontology-build/blob/657356c330692cade6741347772f67eda10f2c18/zpgen/src/main/java/de/charite/zpgen/ZPGen.java#L426). I wonder this is a simple typo of "http://zfin.org/definition/source_information" or other incomplete urls.

**Comment by drseb** [comment]
Not sure I understand: Would replacing "http://zfin/definition/source_information" with "http://zfin.org/definition/source_information"  be sufficient here?

**Comment by yy20716** [comment]
Apologies for a late reply. 
 
- I believe that there must be some reasons that you had to define and use that custom annotation property, <http://zfin/definition/source_information>. Unfortunately, that property is not a valid form of IRI, so some RDF parsers currently complain when importing your data. So I just wanted to say that you could modify its hostname such as <http://zfin.org/definition/source_information> so that it can be syntactically valid.

- I am not an expert about refining ontologies, but If you just wanted to use that property to list equivalent or related classes from other ontologies, I wonder whether you could consider employing some commonly used properties such as rdfs:seeAlso, skos:related, or skos:relatedMatch instead of yours. Thank you.
